version: "3.9"

services:

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5438:5432"