server:
  port: 8080

spring:
  profiles:
    active: parallel

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          generate_statistics: true
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

cache:
  rates:
    update:
      schedule: "0 0 17 * * MON-FRI"
  genres:
    update:
      schedule: 14400000

nbu:
  exchange:
    rate:
      url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange"

token:
  expiration:
    time: 7200000

logging:
  pattern:
    level: "DEBUG"
  file:
    path: "./logs/movieland"
  logback:
    rolling-policy:
      max-file-size: "5MB"
  level:
    org.hibernate:
      sql: debug
      orm:
        jdbc:
          bind: trace
          root: trace
      cache: debug

