server:
  port: ${PORT:8080}

spring:
  datasource:
    username: postgres
    password: postgrsql098
    url: jdbc:postgresql://localhost:5432/movieland
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: false

# intervals for update GenreCache and RateCache
cache:
  genres_interval: "0 0 0/4 * * *"
  rates_interval: "0 0 0 */24 * *"

logging:
  pattern:
    level: "DEBUG"
  file:
    path: "./logs/movieland"
  logback:
    rolling-policy:
      max-file-size: "5MB"

