server:
  port: ${PORT:8080}

spring:
  datasource:
    username: postgres
    password: postgrsql098
    url: jdbc:postgresql://localhost:5432/movieland
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379

cache:
  rates:
    update:
      schedule: "0 0 17 * * MON-FRI"
  genres:
    update:
      schedule: 14400000

nbu:
  exchange:
    rate:
      url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange"

token:
  expiration:
    time: 7200000

logging:
  pattern:
    level: "DEBUG"
  file:
    path: "./logs/movieland"
  logback:
    rolling-policy:
      max-file-size: "5MB"
  level:
    org.hibernate:
      sql: debug
      orm:
        jdbc:
          bind: trace
          root: trace

