CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 20;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY DEFAULT nextval('users_id_seq'),
    name VARCHAR(255) NOT NULL
);